### ISSUE TITLE
Cannot connect to XRDP

### ISSUE THREAD

**Issue by mdenty** [Devolutions/IronRDP#314]
I have some Ubuntu Linux servers running XRDP (0.9.12 and 0.9.17)

The connection always fails with this error message:
```
Connection error: [TLS upgrade] custom error, caused by: received corrupt message of type InvalidContentType
```

It works fine with a Windows 11 ARM VM.

**Comment by mdenty** [comment]
Sure, you'll find the log file attached.
[rustls_ironrdp-client.log](https://github.com/Devolutions/IronRDP/files/13558006/rustls_ironrdp-client.log)

After that log recording, I have tried to change in Cargo.toml file (client) the TLS feature:

```toml
[features]
# default = ["rustls"]
default = ["native-tls"]
rustls = ["ironrdp-tls/rustls"]
native-tls = ["ironrdp-tls/native-tls"]
```
and I have the exact same error message (it does not seem to activate native-tls).

Then, I also changed to `native-tls` in `ironrdp-tls/Cargo.toml` file, the error message is different :
```
Connection error: [TLS upgrade] custom error, caused by: connection closed via error
```
I've also changed the `IRONRDP_LOG` variable to `rustls=trace,native-tls=trace,tokio-native-tls=trace,tokio-rustls=trace` but the log file stays empty.

Here the call stack if useful.
<img width="746" alt="image" src="https://github.com/Devolutions/IronRDP/assets/10026688/0abb51f3-7035-4a19-8591-32660c1bbb0f">
